OctoBotSharp.Web/Areas/Admin/Controllers/GlobalConfigController.cs
using OctoBotSharp.Web.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OctoBotSharp.Domain;
using OctoBotSharp.Service;
using AutoMapper;
using OctoBotSharp.Web.Areas.Admin.Models;
using OctoBotSharp.Data.UnitOfWork;

namespace OctoBotSharp.Web.Areas.Admin.Controllers
{
    [Auth(AuthRole.GlobalConfig)]
    public class GlobalConfigController : Controller
    {
        private readonly IGlobalConfigService _configService;
        private readonly IUnitOfWork _uow;

        public GlobalConfigController(IGlobalConfigService configService, IUnitOfWork uow)
        {
            _configService = configService;
            _uow = uow;
        }

        public ActionResult Edit()
        {
            var config = _configService.GetConfig();

            var vm = Mapper.Map<GlobalConfig, GlobalConfigViewModel>(config);

            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(GlobalConfigViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            var existingDomain = _configService.GetConfig();

            var domain = Mapper.Map<GlobalConfigViewModel, GlobalConfig>(vm, existingDomain);

            _configService.UpdateConfig(domain);
            _uow.SaveChanges();

            return RedirectToAction("Edit");
        }
    }
}

OctoBotSharp.Web/Areas/Admin/Controllers/ItemDefinitionsController.cs
using AutoMapper;
using OctoBotSharp.Data.UnitOfWork;
using OctoBotSharp.Domain;
using OctoBotSharp.Service;
using OctoBotSharp.Web.Areas.Admin.Models;
using OctoBotSharp.Web.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OctoBotSharp.Web.Areas.Admin.Controllers
{
    [Auth(AuthRole.ItemDefinitions)]
    public class ItemDefinitionsController : Controller
    {
        private readonly IService<ItemDefinition> _service;
        private readonly IUnitOfWork _uow;

        public ItemDefinitionsController(IService<ItemDefinition> service, IUnitOfWork uow)
        {
            _service = service;
            _uow = uow;
        }

        public ActionResult Index()
        {
            var items = _service.GetAll()
                .Select(Mapper.Map<ItemDefinition, ItemDefinitionSummaryViewModel>);

            return View(items);
        }

        public ActionResult Detail(int id)
        {
            var item = _service.Find(id);

            if (item == null)
                return HttpNotFound();

            var model = Mapper.Map<ItemDefinition, ItemDefinitionDetailViewModel>(item);

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ItemDefinitionViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var domainModel = Mapper.Map<ItemDefinitionViewModel, ItemDefinition>(model, ItemDefinition.Create());

            _service.Insert(domainModel);
            _uow.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var item = _service.Find(id);
            if (item == null)
                return HttpNotFound();

            var model = Mapper.Map<ItemDefinition, ItemDefinitionViewModel>(item);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ItemDefinitionViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var existingItem = _service.Find(model.Id);
            if (existingItem == null)
                return HttpNotFound();

            var updatedModel = Mapper.Map<ItemDefinitionViewModel, ItemDefinition>(model, existingItem);

            _service.Update(updatedModel);
            _uow.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

OctoBotSharp.Web/Areas/Admin/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using OctoBotSharp.Domain;
using OctoBotSharp.Web.Infrastructure;
using OctoBotSharp.Service;
using AutoMapper;
using Microsoft.AspNet.Identity;
using OctoBotSharp.Web.Areas.Admin.Models;
using OctoBotSharp.Data.Identity;

namespace OctoBotSharp.Web.Areas.Admin.Controllers
{
    [Auth(AuthRole.UserManagement)]
    public class UserManagementController : Controller
    {
        private readonly IService<OctoUser> _userService;
        private readonly OctoUserManager _userManager;
        private readonly OctoRoleManager _roleManager;

        public UserManagementController(IService<OctoUser> userService, OctoUserManager userManager, OctoRoleManager roleManager)
        {
            _userService = userService;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public ActionResult Index()
        {
            var summary = _userService.GetAll()
                .Select(Mapper.Map<OctoUser, UserSummaryViewModel>)
                .ToList();

            return View(summary);
        }

        public ActionResult Detail(int id)
        {
            var user = _userManager.FindById(id);
            if (user == null)
                return HttpNotFound();

            var viewModel = Mapper.Map<OctoUser, UserDetailViewModel>(user);

            return View(viewModel);
        }

        public ActionResult Permissions(int id)
        {
            var user = _userManager.FindById(id);

            if (user == null)
                return HttpNotFound();

            var availableRoles = _roleManager.Roles.Select(x => x.Name).ToList();
            var givenRoles = _userManager.GetRoles(id);

            var viewModel = new UserPermissionsViewModel()
            {
                UserId = id,
                UserName = user.UserName,
                Roles = availableRoles.ToDictionary(key => key, value => givenRoles.Contains(value))
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult SetPermissions(UserPermissionsViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var user = _userManager.FindById(model.UserId);
            if (user == null)
                return HttpNotFound();

            var currentRoles = _userManager.GetRoles(model.UserId);
            var rolesToRemove = model.Roles.Where(x => !x.Value && currentRoles.Contains(x.Key)).Select(x => x.Key).ToArray();
            var rolesToAdd = model.Roles.Where(x => x.Value && !currentRoles.Contains(x.Key)).Select(x => x.Key).ToArray();

            var removeResult = _userManager.RemoveFromRoles(model.UserId, rolesToRemove);
            if (!removeResult.Succeeded)
            {
                ModelState.AddModelError("", removeResult.Errors.First());
                return View(model);
            }

            var addResult = _userManager.AddToRoles(model.UserId, rolesToAdd);
            if (!addResult.Succeeded)
            {
                ModelState.AddModelError("", removeResult.Errors.First());
                return View(model);
            }

            return RedirectToAction("Index");
        }
    }
}

OctoBotSharp.Web/Controllers/MembersController.cs
using AutoMapper;
using OctoBotSharp.Data.Identity;
using OctoBotSharp.Domain;
using OctoBotSharp.Web.Models.Members;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OctoBotSharp.Web.Controllers
{
    public class MembersController : Controller
    {
        private readonly OctoUserManager _userManager;

        public MembersController(OctoUserManager userManager)
        {
            _userManager = userManager;
        }

        public ActionResult Index()
        {
            var vm = _userManager.Users.Select(Mapper.Map<OctoUser, UserSummary>);

            return View(vm);
        }
    }
}

OctoBotSharp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title · OctoBotSharp</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    @Html.Partial("_Menu")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

OctoBotSharp.Web/Views/Shared/_Menu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            @if (User.Identity.IsAuthenticated)
            {
                Html.RenderPartial("_MenuSecure");
            }
            else
            {
                Html.RenderPartial("_MenuUnsecure");
            }
        </div>
    </div>
</div>

OctoBotSharp.Web/Views/Shared/_MenuSecure.cshtml
@using OctoBotSharp.Domain

<ul class="nav navbar-nav">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin <span class="caret"></span></a>
        <ul class="dropdown-menu">
            @if (User.IsInRole(AuthRole.UserManagement))
            {
                <li><a href="@Url.Action("Index", "UserManagement", new { Area = "Admin" })">User Management</a></li>
            }
            
            @if (User.IsInRole(AuthRole.ItemDefinitions))
            {
                <li><a href="@Url.Action("Index", "ItemDefinitions", new { Area = "Admin" })">Item Definitions</a></li>
            }
            
            @if (User.IsInRole(AuthRole.GlobalConfig))
            {
                <li><a href="@Url.Action("Edit", "GlobalConfig", new { Area = "Admin" })">Global Config</a></li>
            }
        </ul>
    </li>
    <li><a href="@Url.Action("Index", "Members", new { Area = "" })">Members</a></li>
</ul>

OctoBotSharp.Web/Views/Shared/_MenuUnsecure.cshtml
<ul class="nav navbar-nav navbar-right">
    <li><a href="@Url.Action("Index", "Auth")">Sign In</a></li>
    <li><a href="@Url.Action("Register", "Auth")">Register</a></li>
</ul>