OctoBotSharp.Web/Areas/Admin/Controllers/UserBalanceController.cs
using OctoBotSharp.Data.Identity;
using OctoBotSharp.Data.UnitOfWork;
using OctoBotSharp.Domain;
using OctoBotSharp.Service;
using OctoBotSharp.Web.Areas.Admin.Models;
using OctoBotSharp.Web.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OctoBotSharp.Web.Areas.Admin.Controllers
{
    [Auth(AuthRole.UserFinancesAdjustment)]
    public class UserBalanceController : Controller
    {
        private readonly ITransactionService _trnxService;
        private readonly OctoUserManager _userManager;
        private readonly IUnitOfWork _uow;

        public UserBalanceController(ITransactionService trnxService, OctoUserManager userManager, IUnitOfWork uow)
        {
            _trnxService = trnxService;
            _userManager = userManager;
            _uow = uow;
        }

        public async Task<ActionResult> Adjust(int id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return HttpNotFound();

            var model = new UserBalanceAdjust()
            {
                UserId = user.Id,
                UserName = user.UserName,
                CurrentBalance = user.Money,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Adjust(UserBalanceAdjust adjustment)
        {
            if (!ModelState.IsValid)
                return View(adjustment);

            var user = await _userManager.FindByIdAsync(adjustment.UserId);
            if (user == null)
            {
                ModelState.AddModelError("UserId", "Cannot find user");
                return View(adjustment);
            }

            var result = _trnxService.AdjustBalance(user, adjustment.Amount, adjustment.Reason);

            if (!result.Success)
            {
                foreach (var err in result.Errors)
                    ModelState.AddModelError("", err);

                return View(adjustment);
            }

            _uow.SaveChanges();

            return RedirectToAction("Detail", "UserManagement", new { Id = adjustment.UserId });
        }
    }
}

OctoBotSharp.Web/Areas/Admin/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using OctoBotSharp.Domain;
using OctoBotSharp.Web.Infrastructure;
using OctoBotSharp.Service;
using AutoMapper;
using Microsoft.AspNet.Identity;
using OctoBotSharp.Web.Areas.Admin.Models;
using OctoBotSharp.Data.Identity;

namespace OctoBotSharp.Web.Areas.Admin.Controllers
{
    [Auth(AuthRole.UserManagement)]
    public class UserManagementController : Controller
    {
        private readonly IService<OctoUser> _userService;
        private readonly OctoUserManager _userManager;
        private readonly OctoRoleManager _roleManager;

        public UserManagementController(IService<OctoUser> userService, OctoUserManager userManager, OctoRoleManager roleManager)
        {
            _userService = userService;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public ActionResult Index()
        {
            var summary = _userService.GetAll()
                .Select(Mapper.Map<OctoUser, UserSummaryViewModel>)
                .ToList();

            return View(summary);
        }

        public ActionResult Detail(int id)
        {
            var user = _userManager.FindById(id);
            if (user == null)
                return HttpNotFound();

            var viewModel = Mapper.Map<OctoUser, UserDetailViewModel>(user);

            return View(viewModel);
        }

        public ActionResult Permissions(int id)
        {
            var user = _userManager.FindById(id);

            if (user == null)
                return HttpNotFound();

            var availableRoles = _roleManager.Roles.Select(x => x.Name).ToList();
            var givenRoles = _userManager.GetRoles(id);

            var viewModel = new UserPermissionsViewModel()
            {
                UserId = id,
                UserName = user.UserName,
                Roles = availableRoles.ToDictionary(key => key, value => givenRoles.Contains(value))
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult SetPermissions(UserPermissionsViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var user = _userManager.FindById(model.UserId);
            if (user == null)
                return HttpNotFound();

            var currentRoles = _userManager.GetRoles(model.UserId);
            var rolesToRemove = model.Roles.Where(x => !x.Value && currentRoles.Contains(x.Key)).Select(x => x.Key).ToArray();
            var rolesToAdd = model.Roles.Where(x => x.Value && !currentRoles.Contains(x.Key)).Select(x => x.Key).ToArray();

            var removeResult = _userManager.RemoveFromRoles(model.UserId, rolesToRemove);
            if (!removeResult.Succeeded)
            {
                ModelState.AddModelError("", removeResult.Errors.First());
                return View(model);
            }

            var addResult = _userManager.AddToRoles(model.UserId, rolesToAdd);
            if (!addResult.Succeeded)
            {
                ModelState.AddModelError("", removeResult.Errors.First());
                return View(model);
            }

            return RedirectToAction("Index");
        }
    }
}

OctoBotSharp.Web/Areas/Admin/Views/UserManagement/Detail.cshtml
@model OctoBotSharp.Web.Areas.Admin.Models.UserDetailViewModel

@{
    ViewBag.Title = "User Detail";
}

<h2>Detail <small>@Model.UserName</small></h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.UserName)</dt>
        <dd>@Html.DisplayFor(model => model.UserName)</dd>

        <dt>@Html.DisplayNameFor(model => model.Email)</dt>
        <dd>@Html.DisplayFor(model => model.Email)</dd>

        <dt>@Html.DisplayNameFor(model => model.EmailConfirmed)</dt>
        <dd>@Html.DisplayFor(model => model.EmailConfirmed)</dd>

        <dt>@Html.DisplayNameFor(model => model.CurrentBalance)</dt>
        <dd>@Html.DisplayFor(model => model.CurrentBalance)</dd>

        <dt>@Html.DisplayNameFor(model => model.Permissions)</dt>
        <dd>
            <ul class="list-unstyled">
                @foreach(var permission in Model.Permissions)
                {
                    <li>@permission</li>
                }
            </ul>
        </dd>

        <dt>@Html.DisplayNameFor(model => model.Transactions)</dt>
        <dd>
            <table class="table">
                <thead>
                    <tr>
                        <th>Recorded At</th>
                        <th>Type</th>
                        <th>Reason</th>
                        <th>Change Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var trnx in Model.Transactions.OrderBy(x => x.RecorededAt))
                    {
                        <tr>
                            <td>@trnx.RecorededAt</td>
                            <td>@trnx.Type</td>
                            <td>@trnx.Reason</td>
                            <td>@trnx.Change</td>
                        </tr>
                    }
                </tbody>
            </table>
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

OctoBotSharp.Web/Areas/Admin/Views/UserManagement/Index.cshtml
@using OctoBotSharp.Web.Areas.Admin.Models
@using OctoBotSharp.Domain

@model IEnumerable<UserSummaryViewModel>

@{
    ViewBag.Title = "User Management";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Email</th>
            <th>Email Confirmed</th>
            <th>Manage</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>@user.EmailConfirmed</td>
                <td>
                    <ul class="list-inline">
                        <li><a href="@Url.Action("Detail", new { Id = user.Id })">Detail</a></li>
                        <li><a href="@Url.Action("Permissions", new { Id = user.Id })">Permissions</a></li>
                        @if (User.IsInRole(AuthRole.UserFinancesAdjustment))
                        {
                            <li><a href="@Url.Action("Adjust", "UserBalance", new { Id = user.Id })">Adjust Balance</a></li>
                        }
                    </ul>
                </td>
            </tr>
        }
    </tbody>
</table>

OctoBotSharp.Web/Areas/Admin/Views/UserManagement/Permissions.cshtml
@using OctoBotSharp.Web.Areas.Admin.Models

@model UserPermissionsViewModel

@{
    ViewBag.Title = "User Permissions";
}

<h2>@ViewBag.Title <small>@Model.UserName</small></h2>

@using (Html.BeginForm("SetPermissions", "UserManagement"))
{ 
    @Html.HiddenFor(model => model.UserId)
    
    <hr />
    
    <table class="table">
        <thead>
            <tr>
                <th>Role</th>
                <th>Enabled</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var role in Model.Roles)
            {
                <tr>
                    <td>@role.Key</td>
                    <td>@Html.CheckBoxFor(m => m.Roles[role.Key])</td>
                </tr>
            }
        </tbody>
    </table>

    <button class="btn btn-primary" type="submit">Update</button>
    <a class="btn btn-default" href="@Url.Action("Index")" role="button">Cancel</a>
}